SRCEXT = .c
HDREXT = .h
CC     = gcc
CXX    = g++
INC    = lib/
LIB    = lib/



all: hashtb.o

hashtb.o: hashtb.c
	gcc -c hashtb.c

error_function.o: error_function.c
	gcc -c error_function.c

clean:
	rm -rf *.o
